# Generated by Django 2.0.5 on 2018-09-09 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Card_Groups',
            },
        ),
        migrations.CreateModel(
            name='Card_Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Card_Packages',
            },
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('card_group', models.ManyToManyField(to='MyDigitalHealth.Card_Groups')),
                ('card_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyDigitalHealth.Card_Packages')),
            ],
            options={
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='Placeholder', max_length=200)),
                ('card_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyDigitalHealth.Card_Packages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Sorted_Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_group', models.ManyToManyField(to='MyDigitalHealth.Card_Groups')),
                ('card_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyDigitalHealth.Card_Packages')),
                ('cards', models.ManyToManyField(to='MyDigitalHealth.Cards')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sorted_Packages',
            },
        ),
        migrations.AddField(
            model_name='card_groups',
            name='card_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyDigitalHealth.Card_Packages'),
        ),
    ]
