# Generated by Django 2.0.5 on 2018-05-23 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card_Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Card_Groups',
            },
        ),
        migrations.CreateModel(
            name='Card_Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Card_Package',
            },
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('card_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyDigitalHealth.Card_Packages')),
            ],
            options={
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.AddField(
            model_name='card_groups',
            name='card_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyDigitalHealth.Card_Packages'),
        ),
    ]
