# Generated by Django 2.0.5 on 2018-09-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyDigitalHealth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorted_package',
            name='card_group',
        ),
        migrations.RemoveField(
            model_name='sorted_package',
            name='cards',
        ),
    ]
