# Generated by Django 2.0.5 on 2018-05-23 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyDigitalHealth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card_packages',
            options={'verbose_name_plural': 'Card_Packages'},
        ),
    ]
