# Generated by Django 2.0.5 on 2018-09-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDigitalHealth', '0002_auto_20180910_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorted_package',
            name='card_group',
            field=models.ManyToManyField(to='MyDigitalHealth.Card_Groups'),
        ),
        migrations.AddField(
            model_name='sorted_package',
            name='cards',
            field=models.ManyToManyField(to='MyDigitalHealth.Cards'),
        ),
    ]
