# Generated by Django 2.0.5 on 2018-09-10 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyDigitalHealth', '0003_auto_20180910_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorted_package',
            name='card_group',
        ),
        migrations.AddField(
            model_name='sorted_package',
            name='card_group',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='MyDigitalHealth.Card_Groups'),
        ),
        migrations.RemoveField(
            model_name='sorted_package',
            name='cards',
        ),
        migrations.AddField(
            model_name='sorted_package',
            name='cards',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='MyDigitalHealth.Cards'),
        ),
    ]
