# Generated by Django 2.0.5 on 2018-09-10 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyDigitalHealth', '0008_auto_20180910_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_groups',
            name='card_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyDigitalHealth.Card_Packages'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_group',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='MyDigitalHealth.Card_Groups'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyDigitalHealth.Card_Packages'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='card_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyDigitalHealth.Card_Packages'),
        ),
        migrations.AlterField(
            model_name='sorted_package',
            name='card_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyDigitalHealth.Card_Packages'),
        ),
        migrations.AlterField(
            model_name='sorted_package',
            name='cards',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='MyDigitalHealth.Cards'),
        ),
    ]
