# Generated by Django 2.0.5 on 2018-09-10 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyDigitalHealth', '0009_auto_20180910_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorted_package',
            name='card_group',
        ),
        migrations.AddField(
            model_name='sorted_package',
            name='card_group',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='MyDigitalHealth.Card_Groups'),
        ),
    ]
