# Generated by Django 2.0.5 on 2018-09-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDigitalHealth', '0010_auto_20180910_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorted_package',
            name='card_group',
        ),
        migrations.RemoveField(
            model_name='sorted_package',
            name='cards',
        ),
        migrations.AddField(
            model_name='sorted_package',
            name='cards',
            field=models.ManyToManyField(to='MyDigitalHealth.Card_Groups'),
        ),
    ]
