# Generated by Django 2.0.5 on 2018-09-16 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyDigitalHealth', '0014_auto_20180916_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorted_package',
            name='card_group',
        ),
    ]
