# Generated by Django 2.0.5 on 2018-09-16 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyDigitalHealth', '0015_remove_sorted_package_card_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorted_package',
            name='cards',
        ),
        migrations.AddField(
            model_name='sorted_package',
            name='cards',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='MyDigitalHealth.Cards'),
        ),
    ]
